# Generated by Django 5.2.14 on 2026-05-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classifieds", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="classifiedlisting",
            name="hide_price",
            field=models.BooleanField(
                default=False,
                help_text="Show 'Contact for price' instead of the actual price.",
            ),
        ),
    ]
