# Generated by Django 5.2.14 on 2026-05-27 00:03
# Extended with a deduplication step before adding the unique constraint.

from django.db import migrations, models


def deduplicate_emails(apps, schema_editor):
    """
    Before making email unique: find rows with duplicated emails and give each
    duplicate a unique placeholder (email+pk suffix) so the constraint can be
    created.  These placeholder accounts can be cleaned up via the admin after
    migration.
    """
    User = apps.get_model("accounts", "User")
    from django.db.models import Count

    dupes = (
        User.objects.values("email")
        .annotate(cnt=Count("id"))
        .filter(cnt__gt=1)
    )
    for entry in dupes:
        email = entry["email"]
        users = list(User.objects.filter(email=email).order_by("date_joined"))
        # Keep the first (oldest) user untouched; patch the rest
        for user in users[1:]:
            user.email = f"{email}__dup{user.pk}"
            user.save(update_fields=["email"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        # Step 1: fix duplicate emails in existing data
        migrations.RunPython(deduplicate_emails, noop),

        # Step 2: add the unique constraint + relax username
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                help_text="Auto-generated internal identifier.",
                max_length=150,
                unique=True,
            ),
        ),
    ]
