# Generated by Django 5.2.14 on 2026-05-27 08:16

import apps.accounts.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_email_as_username_field"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", apps.accounts.models.BarmhaUserManager()),
            ],
        ),
    ]
