# Generated by Django 5.2.14 on 2026-05-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="realestateagency",
            name="whatsapp",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
