# Generated by Django 6.0.5 on 2026-05-23 07:18

import apps.core.validators
import django.db.models.deletion
import imagekit.models.fields
import parler.fields
import parler.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JobCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=50, unique=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CompanyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    imagekit.models.fields.ProcessedImageField(
                        blank=True,
                        null=True,
                        upload_to="jobs/companies/logos/",
                        validators=[
                            apps.core.validators.validate_image_size,
                            apps.core.validators.validate_image_type,
                        ],
                    ),
                ),
                ("industry", models.CharField(blank=True, max_length=100)),
                (
                    "size",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1-10", "1-10"),
                            ("11-50", "11-50"),
                            ("51-200", "51-200"),
                            ("200+", "200+"),
                        ],
                        max_length=10,
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.location",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="company_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="FreelancerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skills", models.JSONField(default=list)),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                ("currency", models.CharField(default="SYP", max_length=5)),
                ("portfolio_url", models.URLField(blank=True)),
                (
                    "avg_rating",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="freelancer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(blank=True, to="jobs.jobcategory"),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="JobListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full Time"),
                            ("part_time", "Part Time"),
                            ("contract", "Contract"),
                            ("internship", "Internship"),
                            ("freelance", "Freelance"),
                        ],
                        max_length=15,
                    ),
                ),
                (
                    "experience",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("entry", "Entry"),
                            ("mid", "Mid"),
                            ("senior", "Senior"),
                            ("manager", "Manager"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("any", "Any"),
                            ("male", "Male"),
                            ("female", "Female"),
                        ],
                        default="any",
                        max_length=10,
                    ),
                ),
                ("nationality", models.CharField(blank=True, max_length=100)),
                (
                    "min_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "max_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(default="SYP", max_length=5)),
                ("salary_period", models.CharField(default="month", max_length=10)),
                ("hide_salary", models.BooleanField(default=False)),
                ("is_remote", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("quick_apply", models.BooleanField(default=False)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("applications_count", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="jobs.jobcategory",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to="jobs.companyprofile",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.location",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_featured", "-created_at"],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="JobseekerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cv",
                    models.FileField(
                        blank=True, null=True, upload_to="jobs/seeker_cvs/"
                    ),
                ),
                ("skills", models.JSONField(default=list)),
                ("experience_years", models.PositiveSmallIntegerField(default=0)),
                ("education", models.CharField(blank=True, max_length=200)),
                (
                    "desired_salary",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(default="SYP", max_length=5)),
                ("is_open", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "saved_jobs",
                    models.ManyToManyField(
                        blank=True, related_name="saved_by", to="jobs.joblisting"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobseeker_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CompanyProfileTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="jobs.companyprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "company profile Translation",
                "db_table": "jobs_companyprofile_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("language_code", "master"),
                        name="jobs_companyprofile_translation_uniq_lang",
                    )
                ],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="FreelancerProfileTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("bio", models.TextField(blank=True)),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="jobs.freelancerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "freelancer profile Translation",
                "db_table": "jobs_freelancerprofile_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("language_code", "master"),
                        name="jobs_freelancerprofile_translation_uniq_lang",
                    )
                ],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="JobCategoryTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="jobs.jobcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "job category Translation",
                "db_table": "jobs_jobcategory_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("language_code", "master"),
                        name="jobs_jobcategory_translation_uniq_lang",
                    )
                ],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="JobApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cover_letter", models.TextField(blank=True)),
                ("cv", models.FileField(blank=True, null=True, upload_to="jobs/cvs/")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("viewed", "Viewed"),
                            ("shortlisted", "Shortlisted"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "applicant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="jobs.joblisting",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("job", "applicant")},
            },
        ),
        migrations.CreateModel(
            name="JobListingTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                ("requirements", models.TextField(blank=True)),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="jobs.joblisting",
                    ),
                ),
            ],
            options={
                "verbose_name": "job listing Translation",
                "db_table": "jobs_joblisting_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("language_code", "master"),
                        name="jobs_joblisting_translation_uniq_lang",
                    )
                ],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name="JobseekerProfileTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language_code",
                    models.CharField(
                        db_index=True, max_length=15, verbose_name="Language"
                    ),
                ),
                ("headline", models.CharField(blank=True, max_length=200)),
                (
                    "master",
                    parler.fields.TranslationsForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="translations",
                        to="jobs.jobseekerprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "jobseeker profile Translation",
                "db_table": "jobs_jobseekerprofile_translation",
                "db_tablespace": "",
                "managed": True,
                "default_permissions": (),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("language_code", "master"),
                        name="jobs_jobseekerprofile_translation_uniq_lang",
                    )
                ],
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
