# Generated by Django 5.2.14 on 2026-05-26 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicelisting",
            name="is_remote",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="servicelisting",
            name="max_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="servicelisting",
            name="min_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
