# Generated by Django 5.2.14 on 2026-05-29 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_servicelisting_is_remote_servicelisting_max_price_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="servicelisting",
            options={
                "ordering": [
                    "-is_featured",
                    "-is_promoted",
                    "-updated_at",
                    "-created_at",
                ]
            },
        ),
    ]
