# Generated by Django 6.0.5 on 2026-05-23 07:18

import apps.core.validators
import django.db.models.deletion
import imagekit.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EducationInstitution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "inst_type",
                    models.CharField(
                        choices=[
                            ("nursery", "Nursery"),
                            ("school", "School"),
                            ("university", "University"),
                            ("training", "Training"),
                        ],
                        max_length=15,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "logo",
                    imagekit.models.fields.ProcessedImageField(
                        blank=True,
                        null=True,
                        upload_to="education/logos/",
                        validators=[
                            apps.core.validators.validate_image_size,
                            apps.core.validators.validate_image_type,
                        ],
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("website", models.URLField(blank=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PropertyListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=70)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                (
                    "og_image",
                    imagekit.models.fields.ProcessedImageField(
                        blank=True,
                        null=True,
                        upload_to="seo/og/",
                        validators=[
                            apps.core.validators.validate_image_size,
                            apps.core.validators.validate_image_type,
                        ],
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                (
                    "purpose",
                    models.CharField(
                        choices=[("for_rent", "For Rent"), ("for_sale", "For Sale")],
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("residential", "Residential"),
                            ("commercial", "Commercial"),
                            ("international", "International"),
                        ],
                        max_length=15,
                    ),
                ),
                ("property_type", models.CharField(max_length=30)),
                ("address_detail", models.CharField(blank=True, max_length=300)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=7, max_digits=10, null=True
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "price_per_sqm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(default="SYP", max_length=5)),
                ("price_period", models.CharField(default="month", max_length=10)),
                ("negotiable", models.BooleanField(default=False)),
                ("bedrooms", models.CharField(blank=True, max_length=20)),
                ("bathrooms", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "area_sqm",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "floor_number",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "total_floors",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("office_capacity", models.CharField(blank=True, max_length=20)),
                (
                    "furnishing",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fully_furnished", "Fully Furnished"),
                            ("semi_furnished", "Semi-Furnished"),
                            ("unfurnished", "Unfurnished"),
                            ("fitted", "Fitted"),
                            ("unfitted", "Unfitted"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "contract_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("annual", "Annual Contract"),
                            ("less_1yr", "Less than 1 Year"),
                            ("more_1yr", "More than 1 Year"),
                            ("monthly", "Monthly"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "deposit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1_month", "1 Month"),
                            ("half_month", "1/2 Month"),
                            ("2_months", "2 Months"),
                            ("none", "None"),
                        ],
                        max_length=10,
                    ),
                ),
                ("no_commission", models.BooleanField(default=False)),
                ("kahramaa_included", models.BooleanField(default=False)),
                ("internet_included", models.BooleanField(default=False)),
                ("amenities", models.JSONField(default=list)),
                ("reference_code", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_promoted", models.BooleanField(default=False)),
                ("is_sold_rented", models.BooleanField(default=False)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "agency",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.realestateagency",
                    ),
                ),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.realestateagent",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.location",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="property_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "property_listings",
                "ordering": ["-is_featured", "-is_promoted", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PropertyImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    imagekit.models.fields.ProcessedImageField(
                        upload_to="properties/images/",
                        validators=[
                            apps.core.validators.validate_image_size,
                            apps.core.validators.validate_image_type,
                        ],
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="properties.propertylisting",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="NearbyAmenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amenity_type",
                    models.CharField(
                        choices=[
                            ("metro", "Metro Station"),
                            ("bus", "Bus Stop"),
                            ("school", "School"),
                            ("hospital", "Hospital / Clinic"),
                            ("mall", "Mall / Supermarket"),
                            ("mosque", "Mosque"),
                        ],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("distance_m", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nearby",
                        to="properties.propertylisting",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="propertylisting",
            index=models.Index(
                fields=["purpose", "category", "is_active"],
                name="property_li_purpose_209fb6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="propertylisting",
            index=models.Index(fields=["price"], name="property_li_price_8281d2_idx"),
        ),
        migrations.AddIndex(
            model_name="propertylisting",
            index=models.Index(
                fields=["created_at"], name="property_li_created_51dac5_idx"
            ),
        ),
    ]
