# Generated by Django 5.2.14 on 2026-05-27 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="propertylisting",
            name="hide_price",
            field=models.BooleanField(
                default=False,
                help_text="When True, price is hidden and 'Contact for price' is shown.",
            ),
        ),
    ]
