# Generated by Django 5.2.14 on 2026-05-29 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0003_propertylisting_listing_intent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="propertylisting",
            options={
                "ordering": [
                    "-is_featured",
                    "-is_promoted",
                    "-updated_at",
                    "-created_at",
                ]
            },
        ),
    ]
