# Generated by Django 5.2.14 on 2026-06-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0004_alter_propertylisting_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertylisting",
            name="office_capacity",
            field=models.CharField(blank=True, default=1, max_length=20, null=True),
        ),
    ]
