# Generated by Django 5.2.14 on 2026-05-25 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="locationtranslation",
            old_name="area",
            new_name="name",
        ),
    ]
