# Generated by Django 5.2.14 on 2026-05-29 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DrawnAreaAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                (
                    "polygon_wkt",
                    models.TextField(
                        help_text="WKT POLYGON string, coords are (lng lat)"
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True,
                        help_text="Restrict to one section, or blank for all",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ListingShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("properties", "Properties"),
                            ("vehicles", "Vehicles"),
                            ("classifieds", "Classifieds"),
                            ("jobs", "Jobs"),
                            ("services", "Services"),
                            ("deals", "Deals"),
                            ("events", "Events"),
                        ],
                        max_length=20,
                    ),
                ),
                ("listing_id", models.PositiveIntegerField()),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.RenameField(
            model_name="locationtranslation",
            old_name="area",
            new_name="name",
        ),
        migrations.AddField(
            model_name="location",
            name="location_type",
            field=models.CharField(
                choices=[
                    ("city", "City"),
                    ("town", "Town"),
                    ("village", "Village"),
                    ("area", "Area"),
                    ("district", "District"),
                    ("subdistrict", "Subdistrict"),
                ],
                default="area",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="slug",
            field=models.SlugField(default=1, max_length=140),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="notification",
            name="notif_type",
            field=models.CharField(
                choices=[
                    ("new_message", "New Message"),
                    ("listing_approved", "Listing Approved"),
                    ("listing_expired", "Listing Expired"),
                    ("deal_nearby", "Deal Nearby"),
                    ("application_update", "Application Update"),
                    ("review_received", "Review Received"),
                    ("price_change", "Price Change"),
                    ("listing_shared", "Listing Shared"),
                    ("new_listing_area", "New Listing In Area"),
                    ("system", "System Announcement"),
                ],
                max_length=25,
            ),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                fields=("governorate", "slug"),
                name="unique_location_slug_per_governorate",
            ),
        ),
        migrations.AddField(
            model_name="drawnareaalert",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drawn_area_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="listingshare",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_shares",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="listingshare",
            name="sender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shared_listings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
