# Generated by Django 5.2.14 on 2026-05-27 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_rename_area_locationtranslation_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notif_type",
            field=models.CharField(
                choices=[
                    ("new_message", "New Message"),
                    ("listing_approved", "Listing Approved"),
                    ("listing_expired", "Listing Expired"),
                    ("deal_nearby", "Deal Nearby"),
                    ("application_update", "Application Update"),
                    ("review_received", "Review Received"),
                    ("price_change", "Price Change"),
                    ("listing_shared", "Listing Shared"),
                    ("system", "System Announcement"),
                ],
                max_length=25,
            ),
        ),
        migrations.CreateModel(
            name="ListingShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("properties", "Properties"),
                            ("vehicles", "Vehicles"),
                            ("classifieds", "Classifieds"),
                            ("jobs", "Jobs"),
                            ("services", "Services"),
                            ("deals", "Deals"),
                            ("events", "Events"),
                        ],
                        max_length=20,
                    ),
                ),
                ("listing_id", models.PositiveIntegerField()),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_shares",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shared_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
