# Generated by Django 5.2.14 on 2026-06-03 19:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_listingrating_sitefeedback"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="listingrating",
            name="unique_listing_rating_per_user",
        ),
        migrations.RenameIndex(
            model_name="listingrating",
            new_name="core_listin_section_b3e969_idx",
            old_name="core_listingrating_section_listing_idx",
        ),
        migrations.AlterUniqueTogether(
            name="listingrating",
            unique_together={("user", "section", "listing_id")},
        ),
    ]
