# Generated by Django 5.2.14 on 2026-05-27 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_notification_notif_type_listingshare"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notif_type",
            field=models.CharField(
                choices=[
                    ("new_message", "New Message"),
                    ("listing_approved", "Listing Approved"),
                    ("listing_expired", "Listing Expired"),
                    ("deal_nearby", "Deal Nearby"),
                    ("application_update", "Application Update"),
                    ("review_received", "Review Received"),
                    ("price_change", "Price Change"),
                    ("listing_shared", "Listing Shared"),
                    ("new_listing_area", "New Listing In Area"),
                    ("system", "System Announcement"),
                ],
                max_length=25,
            ),
        ),
        migrations.CreateModel(
            name="DrawnAreaAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                (
                    "polygon_wkt",
                    models.TextField(
                        help_text="WKT POLYGON string, coords are (lng lat)"
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        blank=True,
                        help_text="Restrict to one section, or blank for all",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drawn_area_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
