# Generated by Django 5.2.14 on 2026-05-27 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_location_location_type_location_slug_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="location_type",
        ),
        migrations.RemoveField(
            model_name="location",
            name="slug",
        ),
    ]
