# Generated by Django 5.2.14 on 2026-05-27 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_location_location_type_remove_location_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="location_type",
            field=models.CharField(
                choices=[
                    ("city", "City"),
                    ("town", "Town"),
                    ("village", "Village"),
                    ("area", "Area"),
                    ("district", "District"),
                    ("subdistrict", "Subdistrict"),
                ],
                default="area",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="slug",
            field=models.SlugField(default=1, max_length=140),
            preserve_default=False,
        ),
    ]
