# Generated by Django 6.0.5 on 2026-05-23 07:18

import apps.core.validators
import django.db.models.deletion
import imagekit.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VehicleMake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "logo",
                    imagekit.models.fields.ProcessedImageField(
                        blank=True,
                        null=True,
                        upload_to="vehicles/makes/",
                        validators=[
                            apps.core.validators.validate_image_size,
                            apps.core.validators.validate_image_type,
                        ],
                    ),
                ),
                ("popular", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Garage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("specializations", models.JSONField(default=list)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RentalCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "logo",
                    imagekit.models.fields.ProcessedImageField(
                        blank=True,
                        null=True,
                        upload_to="vehicles/rental/logos/",
                        validators=[
                            apps.core.validators.validate_image_size,
                            apps.core.validators.validate_image_type,
                        ],
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("website", models.URLField(blank=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Showroom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "logo",
                    imagekit.models.fields.ProcessedImageField(
                        blank=True,
                        null=True,
                        upload_to="vehicles/showrooms/logos/",
                        validators=[
                            apps.core.validators.validate_image_size,
                            apps.core.validators.validate_image_type,
                        ],
                    ),
                ),
                (
                    "cover",
                    imagekit.models.fields.ProcessedImageField(
                        blank=True,
                        null=True,
                        upload_to="vehicles/showrooms/covers/",
                        validators=[
                            apps.core.validators.validate_image_size,
                            apps.core.validators.validate_image_type,
                        ],
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("whatsapp", models.CharField(blank=True, max_length=20)),
                ("description", models.TextField(blank=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VehicleListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=70)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                (
                    "og_image",
                    imagekit.models.fields.ProcessedImageField(
                        blank=True,
                        null=True,
                        upload_to="seo/og/",
                        validators=[
                            apps.core.validators.validate_image_size,
                            apps.core.validators.validate_image_type,
                        ],
                    ),
                ),
                (
                    "listing_type",
                    models.CharField(
                        choices=[("sale", "For Sale"), ("rent", "For Rent")],
                        max_length=10,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("car", "Car"),
                            ("commercial", "Commercial"),
                            ("motorbike", "Motorbike"),
                            ("boat", "Boat"),
                        ],
                        max_length=15,
                    ),
                ),
                ("trim", models.CharField(blank=True, max_length=100)),
                ("year", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(default="SYP", max_length=5)),
                ("negotiable", models.BooleanField(default=False)),
                ("mileage", models.PositiveIntegerField(blank=True, null=True)),
                ("fuel_type", models.CharField(blank=True, max_length=20)),
                ("gear_type", models.CharField(blank=True, max_length=20)),
                ("engine_size", models.CharField(blank=True, max_length=20)),
                ("cylinders", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("wheel_drive", models.CharField(blank=True, max_length=10)),
                ("body_style", models.CharField(blank=True, max_length=30)),
                ("color_exterior", models.CharField(blank=True, max_length=50)),
                ("color_interior", models.CharField(blank=True, max_length=50)),
                ("doors", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("seats", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "condition",
                    models.CharField(
                        blank=True,
                        choices=[("brand_new", "Brand New"), ("used", "Used")],
                        max_length=15,
                    ),
                ),
                ("import_source", models.CharField(blank=True, max_length=100)),
                ("insurance_type", models.CharField(blank=True, max_length=50)),
                ("features", models.JSONField(default=dict)),
                ("under_warranty", models.BooleanField(default=False)),
                ("computer_check", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_promoted", models.BooleanField(default=False)),
                ("is_sold", models.BooleanField(default=False)),
                ("views_count", models.PositiveIntegerField(default=0)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.location",
                    ),
                ),
                (
                    "posted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle_listings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "showroom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="listings",
                        to="vehicles.showroom",
                    ),
                ),
                (
                    "make",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="vehicles.vehiclemake",
                    ),
                ),
            ],
            options={
                "db_table": "vehicle_listings",
                "ordering": ["-is_featured", "-is_promoted", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VehicleImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    imagekit.models.fields.ProcessedImageField(
                        upload_to="vehicles/images/",
                        validators=[
                            apps.core.validators.validate_image_size,
                            apps.core.validators.validate_image_type,
                        ],
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="vehicles.vehiclelisting",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="CarPart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="SYP", max_length=5)),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("used", "Used"),
                            ("refurbished", "Refurbished"),
                        ],
                        default="used",
                        max_length=15,
                    ),
                ),
                (
                    "image",
                    imagekit.models.fields.ProcessedImageField(
                        blank=True,
                        null=True,
                        upload_to="vehicles/parts/",
                        validators=[
                            apps.core.validators.validate_image_size,
                            apps.core.validators.validate_image_type,
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "posted_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="car_parts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "compatible_make",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="vehicles.vehiclemake",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VehicleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "make",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="models",
                        to="vehicles.vehiclemake",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("make", "name")},
            },
        ),
        migrations.AddField(
            model_name="vehiclelisting",
            name="model",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="vehicles.vehiclemodel",
            ),
        ),
        migrations.AddIndex(
            model_name="vehiclelisting",
            index=models.Index(
                fields=["listing_type", "category", "is_active"],
                name="vehicle_lis_listing_ff5897_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="vehiclelisting",
            index=models.Index(fields=["price"], name="vehicle_lis_price_17d8be_idx"),
        ),
        migrations.AddIndex(
            model_name="vehiclelisting",
            index=models.Index(fields=["year"], name="vehicle_lis_year_1cf075_idx"),
        ),
        migrations.AddIndex(
            model_name="vehiclelisting",
            index=models.Index(
                fields=["created_at"], name="vehicle_lis_created_4f4f02_idx"
            ),
        ),
    ]
