# Generated by Django 5.2.14 on 2026-05-26 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehiclelisting",
            name="features",
            field=models.JSONField(default=list),
        ),
    ]
