"""
Django management command: seed Syria governorates and locations from OCHA/HDX Excel workbook.

Place this file at:
    python manage.py seed_syria_locations --xlsx apps\core\management\commands\data\syr_admin_boundaries.xlsx --dry-run

Place the workbook at, for example:
    data/syr_admin_boundaries.xlsx

Run:
    python manage.py seed_syria_locations --xlsx apps\core\management\commands\data\syr_admin_boundaries.xlsx
    python manage.py seed_syria_locations --xlsx apps\core\management\commands\data\syr_admin_boundaries.xlsx --reset

This command intentionally uses only Python stdlib to parse .xlsx files, so your project
will not need pandas/openpyxl just for seeding.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from decimal import Decimal, InvalidOperation
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple
from xml.etree import ElementTree as ET
from zipfile import ZipFile

from django.core.management.base import BaseCommand, CommandError
from django.db import transaction
from django.utils.text import slugify

# TODO: replace locations with your real Django app name.
from apps.core.models import Governorate, Location


GOVERNORATES = [
    {"slug": "damascus", "order": 1, "en": "Damascus", "ar": "دمشق"},
    {"slug": "rif_dimashq", "order": 2, "en": "Rural Damascus", "ar": "ريف دمشق"},
    {"slug": "aleppo", "order": 3, "en": "Aleppo", "ar": "حلب"},
    {"slug": "homs", "order": 4, "en": "Homs", "ar": "حمص"},
    {"slug": "hama", "order": 5, "en": "Hama", "ar": "حماة"},
    {"slug": "latakia", "order": 6, "en": "Latakia", "ar": "اللاذقية"},
    {"slug": "tartus", "order": 7, "en": "Tartus", "ar": "طرطوس"},
    {"slug": "idlib", "order": 8, "en": "Idlib", "ar": "إدلب"},
    {"slug": "deir_ezzor", "order": 9, "en": "Deir ez-Zor", "ar": "دير الزور"},
    {"slug": "hasakah", "order": 10, "en": "Al-Hasakah", "ar": "الحسكة"},
    {"slug": "raqqa", "order": 11, "en": "Raqqa", "ar": "الرقة"},
    {"slug": "daraa", "order": 12, "en": "Daraa", "ar": "درعا"},
    {"slug": "suwayda", "order": 13, "en": "As-Suwayda", "ar": "السويداء"},
    {"slug": "quneitra", "order": 14, "en": "Quneitra", "ar": "القنيطرة"},
]

ADM1_PCODE_TO_SLUG = {
    "SY01": "damascus",
    "SY02": "aleppo",
    "SY03": "rif_dimashq",
    "SY04": "homs",
    "SY05": "hama",
    "SY06": "latakia",
    "SY07": "idlib",
    "SY08": "hasakah",
    "SY09": "deir_ezzor",
    "SY10": "tartus",
    "SY11": "raqqa",
    "SY12": "daraa",
    "SY13": "suwayda",
    "SY14": "quneitra",
}

POPULAR_PLACE_KEYS = {
    "damascus",
    "aleppo",
    "homs",
    "hama",
    "latakia",
    "lattakia",
    "tartous",
    "tartus",
    "idleb",
    "idlib",
    "deir-ez-zor",
    "deir ez-zor",
    "al-hasakeh",
    "al-hasakah",
    "ar-raqqa",
    "raqqa",
    "dar'a",
    "daraa",
    "as-sweida",
    "as-suwayda",
    "quneitra",
    "qamishli",
    "manbij",
    "al bab",
    "azaz",
    "a'zaz",
    "afrin",
    "jableh",
    "baniyas",
    "safita",
    "douma",
    "yabroud",
    "zabadani",
    "abu kamal",
    "al mayadin",
    "nawa",
    "izra",
}

XLSX_NS = {"a": "http://schemas.openxmlformats.org/spreadsheetml/2006/main"}
RELS_NS = {"r": "http://schemas.openxmlformats.org/package/2006/relationships"}
OFFICE_REL_NS = "http://schemas.openxmlformats.org/officeDocument/2006/relationships"


@dataclass(frozen=True)
class LocationPayload:
    governorate_slug: str
    slug: str
    location_type: str
    city_en: str
    name_en: str
    city_ar: str
    name_ar: str
    latitude: Optional[Decimal]
    longitude: Optional[Decimal]
    is_popular: bool


def clean(value) -> str:
    value = str(value or "").strip()
    if value.lower() in {"", "none", "null", "<null>", "nan", "-"}:
        return ""
    return re.sub(r"\s+", " ", value)


def parse_decimal(value) -> Optional[Decimal]:
    value = clean(value)
    if not value:
        return None
    try:
        return Decimal(value)
    except (InvalidOperation, ValueError):
        return None


def make_slug(*parts: str) -> str:
    source = "-".join(clean(part) for part in parts if clean(part))
    value = slugify(source, allow_unicode=False) or slugify(source, allow_unicode=True)
    return value[:140]


def is_popular(*names: str) -> bool:
    return any(clean(name).lower() in POPULAR_PLACE_KEYS for name in names if clean(name))


class SimpleXlsxReader:
    """Small XLSX reader for values-only worksheets generated by HDX/OCHA."""

    def __init__(self, path: Path):
        self.path = path
        self.shared_strings: List[str] = []
        self.sheet_targets: Dict[str, str] = {}

    def __enter__(self):
        self.zip_file = ZipFile(self.path)
        self.shared_strings = self._load_shared_strings()
        self.sheet_targets = self._load_sheet_targets()
        return self

    def __exit__(self, exc_type, exc, tb):
        self.zip_file.close()

    def _load_shared_strings(self) -> List[str]:
        if "xl/sharedStrings.xml" not in self.zip_file.namelist():
            return []

        root = ET.fromstring(self.zip_file.read("xl/sharedStrings.xml"))
        strings = []
        for item in root.findall("a:si", XLSX_NS):
            strings.append("".join(t.text or "" for t in item.findall(".//a:t", XLSX_NS)))
        return strings

    def _load_sheet_targets(self) -> Dict[str, str]:
        rels_root = ET.fromstring(self.zip_file.read("xl/_rels/workbook.xml.rels"))
        rels = {
            rel.attrib["Id"]: rel.attrib["Target"].lstrip("/")
            for rel in rels_root
        }

        workbook_root = ET.fromstring(self.zip_file.read("xl/workbook.xml"))
        targets = {}
        for sheet in workbook_root.findall("a:sheets/a:sheet", XLSX_NS):
            name = sheet.attrib["name"]
            rel_id = sheet.attrib[f"{{{OFFICE_REL_NS}}}id"]
            target = rels[rel_id]
            if not target.startswith("xl/"):
                target = "xl/" + target
            targets[name] = target
        return targets

    @staticmethod
    def _column_index(cell_reference: str) -> int:
        letters = "".join(ch for ch in cell_reference if ch.isalpha())
        index = 0
        for ch in letters.upper():
            index = index * 26 + ord(ch) - 64
        return index - 1

    def _cell_value(self, cell) -> str:
        value_node = cell.find("a:v", XLSX_NS)
        if value_node is None:
            return ""

        value = value_node.text or ""
        if cell.attrib.get("t") == "s" and value:
            return self.shared_strings[int(value)]
        return value

    def rows(self, sheet_name: str) -> Iterable[Dict[str, str]]:
        if sheet_name not in self.sheet_targets:
            return []

        root = ET.fromstring(self.zip_file.read(self.sheet_targets[sheet_name]))
        parsed_rows: List[List[str]] = []

        for row in root.findall("a:sheetData/a:row", XLSX_NS):
            values: List[str] = []
            for cell in row.findall("a:c", XLSX_NS):
                idx = self._column_index(cell.attrib.get("r", "A1"))
                while len(values) <= idx:
                    values.append("")
                values[idx] = self._cell_value(cell)
            parsed_rows.append(values)

        if not parsed_rows:
            return []

        headers = [clean(header) for header in parsed_rows[0]]
        result = []
        for row in parsed_rows[1:]:
            if not any(clean(value) for value in row):
                continue
            padded = row + [""] * (len(headers) - len(row))
            result.append({headers[i]: clean(padded[i]) for i in range(len(headers))})
        return result


def payload_from_admin2(row: Dict[str, str]) -> Optional[LocationPayload]:
    gov_slug = ADM1_PCODE_TO_SLUG.get(row.get("adm1_pcode", ""))
    if not gov_slug:
        return None

    adm2_en = row.get("adm2_name", "")
    adm2_ar = row.get("adm2_name1", "") or adm2_en
    pcode = row.get("adm2_pcode", "")
    slug = make_slug("district", pcode or adm2_en)

    if not adm2_en or not slug:
        return None

    return LocationPayload(
        governorate_slug=gov_slug,
        slug=slug,
        location_type="district",
        city_en=adm2_en,
        name_en="",
        city_ar=adm2_ar,
        name_ar="",
        latitude=parse_decimal(row.get("center_lat")),
        longitude=parse_decimal(row.get("center_lon")),
        is_popular=is_popular(adm2_en),
    )


def payload_from_admin3(row: Dict[str, str]) -> Optional[LocationPayload]:
    gov_slug = ADM1_PCODE_TO_SLUG.get(row.get("adm1_pcode", ""))
    if not gov_slug:
        return None

    adm2_en = row.get("adm2_name", "")
    adm2_ar = row.get("adm2_name1", "") or adm2_en
    adm3_en = row.get("adm3_name", "")
    adm3_ar = row.get("adm3_name1", "") or adm3_en
    pcode = row.get("adm3_pcode", "")
    slug = make_slug("subdistrict", pcode or adm3_en)

    if not adm3_en or not slug:
        return None

    return LocationPayload(
        governorate_slug=gov_slug,
        slug=slug,
        location_type="subdistrict",
        city_en=adm2_en or adm3_en,
        name_en=adm3_en,
        city_ar=adm2_ar or adm3_ar,
        name_ar=adm3_ar,
        latitude=parse_decimal(row.get("center_lat")),
        longitude=parse_decimal(row.get("center_lon")),
        is_popular=is_popular(adm2_en, adm3_en),
    )


def classify_populated_place(row: Dict[str, str]) -> str:
    title = clean(row.get("popplaceclasstitle", "")).lower()
    feature = clean(row.get("featurename_en", "")).lower()

    if "neighborhood" in title:
        return "area"
    if feature in POPULAR_PLACE_KEYS:
        return "city"
    return "village"


def payload_from_populated_place(row: Dict[str, str]) -> Optional[LocationPayload]:
    gov_slug = ADM1_PCODE_TO_SLUG.get(row.get("adm1_pcode", ""))
    if not gov_slug:
        return None

    feature_en = row.get("featurename_en", "") or row.get("adm4_en", "")
    feature_ar = row.get("featurename_ar", "") or row.get("adm4_ar", "") or feature_en
    adm3_en = row.get("adm3_en", "")
    adm3_ar = row.get("adm3_ar", "") or adm3_en
    adm2_en = row.get("adm2_en", "")
    adm2_ar = row.get("adm2_ar", "") or adm2_en
    pcode = row.get("pcode", "") or row.get("adm4_pcode", "")
    slug = make_slug("place", pcode or feature_en)

    if not feature_en or not slug:
        return None

    city_en = adm3_en or adm2_en or feature_en
    city_ar = adm3_ar or adm2_ar or feature_ar

    return LocationPayload(
        governorate_slug=gov_slug,
        slug=slug,
        location_type=classify_populated_place(row),
        city_en=city_en,
        name_en=feature_en,
        city_ar=city_ar,
        name_ar=feature_ar,
        latitude=parse_decimal(row.get("point_y")),
        longitude=parse_decimal(row.get("point_x")),
        is_popular=is_popular(feature_en, adm3_en, adm2_en),
    )


def payload_from_neighborhood(row: Dict[str, str]) -> Optional[LocationPayload]:
    gov_slug = ADM1_PCODE_TO_SLUG.get(row.get("adm1_pcode", ""))
    if not gov_slug:
        return None

    neighborhood_en = row.get("neighborhoodname_en", "")
    neighborhood_ar = row.get("neighborhoodname_ar", "") or neighborhood_en
    area_en = row.get("areaname_en", "")
    area_ar = row.get("areaname_ar", "") or area_en
    adm3_en = row.get("adm3_en", "")
    adm3_ar = row.get("adm3_ar", "") or adm3_en
    pcode = row.get("neighborhoodpcode", "")
    slug = make_slug("neighborhood", pcode or neighborhood_en)

    if not neighborhood_en or not slug:
        return None

    city_en = area_en or adm3_en or neighborhood_en
    city_ar = area_ar or adm3_ar or neighborhood_ar

    return LocationPayload(
        governorate_slug=gov_slug,
        slug=slug,
        location_type="area",
        city_en=city_en,
        name_en=neighborhood_en,
        city_ar=city_ar,
        name_ar=neighborhood_ar,
        latitude=None,
        longitude=None,
        is_popular=is_popular(neighborhood_en, area_en, adm3_en),
    )


def collect_payloads(reader: SimpleXlsxReader, include_neighborhoods: bool = True) -> List[LocationPayload]:
    payloads: List[LocationPayload] = []
    seen: set[Tuple[str, str]] = set()

    sources = [
        ("syr_admin2", payload_from_admin2),
        ("syr_admin3", payload_from_admin3),
        ("syr_populatedplaces", payload_from_populated_place),
    ]

    if include_neighborhoods:
        sources.append(("syr_neighborhoods", payload_from_neighborhood))

    for sheet_name, builder in sources:
        for row in reader.rows(sheet_name):
            payload = builder(row)
            if not payload:
                continue
            key = (payload.governorate_slug, payload.slug)
            if key in seen:
                continue
            seen.add(key)
            payloads.append(payload)

    return payloads


class Command(BaseCommand):
    help = "Seed Syria governorates, districts, subdistricts, populated places, and neighborhoods from the OCHA/HDX workbook."

    def add_arguments(self, parser):
        parser.add_argument(
            "--xlsx",
            required=True,
            help="Path to syr_admin_boundaries.xlsx.",
        )
        parser.add_argument(
            "--reset",
            action="store_true",
            help="Delete existing seeded Syria locations/governorates before seeding.",
        )
        parser.add_argument(
            "--dry-run",
            action="store_true",
            help="Read the workbook and show counts without saving changes.",
        )
        parser.add_argument(
            "--skip-neighborhoods",
            action="store_true",
            help="Skip the syr_neighborhoods sheet. Populated places are still imported.",
        )

    @transaction.atomic
    def handle(self, *args, **options):
        xlsx_path = Path(options["xlsx"])
        if not xlsx_path.exists():
            raise CommandError(f"Workbook not found: {xlsx_path}")

        with SimpleXlsxReader(xlsx_path) as reader:
            payloads = collect_payloads(
                reader,
                include_neighborhoods=not options["skip_neighborhoods"],
            )

        if options["dry_run"]:
            self.print_summary(payloads, dry_run=True)
            transaction.set_rollback(True)
            return

        if options["reset"]:
            slugs = [item["slug"] for item in GOVERNORATES]
            Location.objects.filter(governorate__slug__in=slugs).delete()
            Governorate.objects.filter(slug__in=slugs).delete()
            self.stdout.write(self.style.WARNING("Deleted existing Syria governorates and locations."))

        governorates = self.seed_governorates()

        created = 0
        updated = 0

        for payload in payloads:
            gov = governorates[payload.governorate_slug]

            location, was_created = Location.objects.get_or_create(
                governorate=gov,
                slug=payload.slug,
                defaults={
                    "location_type": payload.location_type,
                    "latitude": payload.latitude,
                    "longitude": payload.longitude,
                    "is_popular": payload.is_popular,
                },
            )

            location.location_type = payload.location_type
            location.latitude = payload.latitude
            location.longitude = payload.longitude
            location.is_popular = payload.is_popular

            location.set_current_language("en")
            location.city = payload.city_en
            location.name = payload.name_en
            location.save()

            location.set_current_language("ar")
            location.city = payload.city_ar
            location.name = payload.name_ar
            location.save()

            if was_created:
                created += 1
            else:
                updated += 1

        self.print_summary(payloads, dry_run=False, created=created, updated=updated)

    def seed_governorates(self) -> Dict[str, Governorate]:
        governorates: Dict[str, Governorate] = {}

        for item in GOVERNORATES:
            gov, _ = Governorate.objects.get_or_create(
                slug=item["slug"],
                defaults={"order": item["order"], "is_active": True},
            )

            gov.order = item["order"]
            gov.is_active = True

            gov.set_current_language("en")
            gov.name = item["en"]
            gov.save()

            gov.set_current_language("ar")
            gov.name = item["ar"]
            gov.save()

            governorates[item["slug"]] = gov

        return governorates

    def print_summary(self, payloads: List[LocationPayload], dry_run: bool, created: int = 0, updated: int = 0):
        by_type: Dict[str, int] = {}
        by_governorate: Dict[str, int] = {}

        for payload in payloads:
            by_type[payload.location_type] = by_type.get(payload.location_type, 0) + 1
            by_governorate[payload.governorate_slug] = by_governorate.get(payload.governorate_slug, 0) + 1

        self.stdout.write("\nLocation counts by type:")
        for location_type in sorted(by_type):
            self.stdout.write(f"  {location_type}: {by_type[location_type]}")

        self.stdout.write("\nLocation counts by governorate:")
        for gov in [item["slug"] for item in GOVERNORATES]:
            self.stdout.write(f"  {gov}: {by_governorate.get(gov, 0)}")

        if dry_run:
            self.stdout.write(self.style.WARNING(f"\nDry run only. Parsed locations: {len(payloads)}."))
        else:
            self.stdout.write(
                self.style.SUCCESS(
                    f"\nSeed complete. Governorates: {len(GOVERNORATES)}. "
                    f"Locations parsed: {len(payloads)}. Created: {created}. Updated: {updated}."
                )
            )
