CHOICES_REGISTRY = {
    "property_purpose": [
        {"value": "for_rent", "label_en": "For Rent", "label_ar": "للإيجار"},
        {"value": "for_sale", "label_en": "For Sale", "label_ar": "للبيع"},
    ],
    "property_category": [
        {"value": "residential",   "label_en": "Residential",   "label_ar": "سكني"},
        {"value": "commercial",    "label_en": "Commercial",    "label_ar": "تجاري"},
        {"value": "international", "label_en": "International", "label_ar": "دولي"},
    ],
    "furnishing": [
        {"value": "fully_furnished", "label_en": "Fully Furnished", "label_ar": "مفروش بالكامل"},
        {"value": "semi_furnished",  "label_en": "Semi-Furnished",  "label_ar": "مفروش جزئياً"},
        {"value": "unfurnished",     "label_en": "Unfurnished",     "label_ar": "غير مفروش"},
        {"value": "fitted",          "label_en": "Fitted",          "label_ar": "مجهز"},
        {"value": "unfitted",        "label_en": "Unfitted",        "label_ar": "غير مجهز"},
    ],
    "contract_type": [
        {"value": "annual",   "label_en": "Annual Contract",  "label_ar": "عقد سنوي"},
        {"value": "less_1yr", "label_en": "Less than 1 Year", "label_ar": "أقل من سنة"},
        {"value": "more_1yr", "label_en": "More than 1 Year", "label_ar": "أكثر من سنة"},
        {"value": "monthly",  "label_en": "Monthly",          "label_ar": "شهري"},
    ],
    "property_deposit": [
        {"value": "none",       "label_en": "No Deposit",     "label_ar": "بدون كفالة"},
        {"value": "half_month", "label_en": "Half Month",     "label_ar": "نصف شهر"},
        {"value": "1_month",    "label_en": "1 Month",        "label_ar": "شهر واحد"},
        {"value": "2_months",   "label_en": "2 Months",       "label_ar": "شهران"},
    ],
    "property_price_period": [
        {"value": "monthly",  "label_en": "Per Month",   "label_ar": "شهرياً"},
        {"value": "yearly",   "label_en": "Per Year",    "label_ar": "سنوياً"},
        {"value": "daily",    "label_en": "Per Day",     "label_ar": "يومياً"},
        {"value": "weekly",   "label_en": "Per Week",    "label_ar": "أسبوعياً"},
        {"value": "quarterly","label_en": "Per Quarter", "label_ar": "ربع سنوي"},
    ],
    "vehicle_fuel_type": [
        {"value": "petrol",   "label_en": "Petrol",   "label_ar": "بنزين"},
        {"value": "diesel",   "label_en": "Diesel",   "label_ar": "ديزل"},
        {"value": "electric", "label_en": "Electric", "label_ar": "كهربائي"},
        {"value": "hybrid",   "label_en": "Hybrid",   "label_ar": "هجين"},
        {"value": "gas",      "label_en": "Gas",      "label_ar": "غاز"},
    ],
    "vehicle_gear_type": [
        {"value": "automatic", "label_en": "Automatic",      "label_ar": "أوتوماتيك"},
        {"value": "manual",    "label_en": "Manual",         "label_ar": "يدوي"},
        {"value": "semi_auto", "label_en": "Semi-Automatic", "label_ar": "نصف أوتوماتيك"},
    ],
    "vehicle_body_style": [
        {"value": "suv",         "label_en": "SUV",         "label_ar": "دفع رباعي"},
        {"value": "sedan",       "label_en": "Sedan",       "label_ar": "سيدان"},
        {"value": "hatchback",   "label_en": "Hatchback",   "label_ar": "هاتشباك"},
        {"value": "coupe",       "label_en": "Coupe",       "label_ar": "كوبيه"},
        {"value": "pickup",      "label_en": "Pickup",      "label_ar": "بيك أب"},
        {"value": "van",         "label_en": "Van",         "label_ar": "فان"},
        {"value": "convertible", "label_en": "Convertible", "label_ar": "مكشوف"},
        {"value": "crossover",   "label_en": "Crossover",   "label_ar": "كروس أوفر"},
        {"value": "wagon",       "label_en": "Station Wagon","label_ar": "واغن"},
        {"value": "minivan",     "label_en": "Minivan",     "label_ar": "ميني فان"},
    ],
    "vehicle_condition": [
        {"value": "brand_new", "label_en": "Brand New", "label_ar": "جديد"},
        {"value": "used",      "label_en": "Used",      "label_ar": "مستعمل"},
    ],
    "vehicle_wheel_drive": [
        {"value": "all",   "label_en": "All-Wheel Drive",   "label_ar": "دفع كلي"},
        {"value": "front", "label_en": "Front-Wheel Drive", "label_ar": "دفع أمامي"},
        {"value": "rear",  "label_en": "Rear-Wheel Drive",  "label_ar": "دفع خلفي"},
        {"value": "4wd",   "label_en": "4WD",               "label_ar": "4WD"},
    ],
    "user_type": [
        {"value": "individual",  "label_en": "Individual",           "label_ar": "فرد"},
        {"value": "agent",       "label_en": "Real Estate Agent",    "label_ar": "وكيل عقاري"},
        {"value": "agency",      "label_en": "Real Estate Agency",   "label_ar": "وكالة عقارية"},
        {"value": "company",     "label_en": "Company / Employer",   "label_ar": "شركة / صاحب عمل"},
        {"value": "freelancer",  "label_en": "Freelancer",           "label_ar": "مستقل"},
        {"value": "merchant",    "label_en": "Merchant / Business",  "label_ar": "تاجر / صاحب نشاط"},
    ],
    "governorate": [
        {"value": "damascus",    "label_en": "Damascus",       "label_ar": "دمشق"},
        {"value": "rif_dimashq", "label_en": "Rural Damascus", "label_ar": "ريف دمشق"},
        {"value": "aleppo",      "label_en": "Aleppo",         "label_ar": "حلب"},
        {"value": "homs",        "label_en": "Homs",           "label_ar": "حمص"},
        {"value": "hama",        "label_en": "Hama",           "label_ar": "حماة"},
        {"value": "latakia",     "label_en": "Latakia",        "label_ar": "اللاذقية"},
        {"value": "tartus",      "label_en": "Tartus",         "label_ar": "طرطوس"},
        {"value": "idlib",       "label_en": "Idlib",          "label_ar": "إدلب"},
        {"value": "deir_ezzor",  "label_en": "Deir ez-Zor",   "label_ar": "دير الزور"},
        {"value": "hasakah",     "label_en": "Al-Hasakah",     "label_ar": "الحسكة"},
        {"value": "raqqa",       "label_en": "Raqqa",          "label_ar": "الرقة"},
        {"value": "daraa",       "label_en": "Daraa",          "label_ar": "درعا"},
        {"value": "suwayda",     "label_en": "As-Suwayda",     "label_ar": "السويداء"},
        {"value": "quneitra",    "label_en": "Quneitra",       "label_ar": "القنيطرة"},
    ],
    "currency": [
        {"value": "SYP", "label_en": "Syrian Pound",  "label_ar": "ليرة سورية",   "symbol": "ل.س"},
        {"value": "USD", "label_en": "US Dollar",     "label_ar": "دولار أمريكي", "symbol": "$"},
    ],
    "job_type": [
        {"value": "full_time",  "label_en": "Full Time",   "label_ar": "دوام كامل"},
        {"value": "part_time",  "label_en": "Part Time",   "label_ar": "دوام جزئي"},
        {"value": "contract",   "label_en": "Contract",    "label_ar": "عقد"},
        {"value": "internship", "label_en": "Internship",  "label_ar": "تدريب"},
        {"value": "freelance",  "label_en": "Freelance",   "label_ar": "مستقل"},
    ],
    "experience_level": [
        {"value": "entry",   "label_en": "Entry Level", "label_ar": "مبتدئ"},
        {"value": "mid",     "label_en": "Mid Level",   "label_ar": "متوسط"},
        {"value": "senior",  "label_en": "Senior",      "label_ar": "خبير"},
        {"value": "manager", "label_en": "Manager",     "label_ar": "مدير"},
    ],
    "deal_type": [
        {"value": "buy1get1",   "label_en": "Buy 1 Get 1",  "label_ar": "اشتر 1 واحصل على 1"},
        {"value": "discount",   "label_en": "Flat Discount", "label_ar": "خصم مباشر"},
        {"value": "bundle",     "label_en": "Bundle",        "label_ar": "حزمة"},
        {"value": "free_trial", "label_en": "Free Trial",    "label_ar": "تجربة مجانية"},
        {"value": "cashback",   "label_en": "Cashback",      "label_ar": "استرداد نقدي"},
    ],
    "classified_condition": [
        {"value": "new",           "label_en": "New",            "label_ar": "جديد"},
        {"value": "used_like_new", "label_en": "Used – Like New","label_ar": "مستعمل كالجديد"},
        {"value": "used_good",     "label_en": "Used – Good",    "label_ar": "مستعمل - جيد"},
        {"value": "used_fair",     "label_en": "Used – Fair",    "label_ar": "مستعمل - مقبول"},
    ],
    "price_type": [
        {"value": "fixed",      "label_en": "Fixed",      "label_ar": "ثابت"},
        {"value": "hourly",     "label_en": "Per Hour",   "label_ar": "بالساعة"},
        {"value": "daily",      "label_en": "Per Day",    "label_ar": "باليوم"},
        {"value": "negotiable", "label_en": "Negotiable", "label_ar": "قابل للتفاوض"},
    ],
    "event_price_type": [
        {"value": "free",     "label_en": "Free",     "label_ar": "مجاني"},
        {"value": "paid",     "label_en": "Paid",     "label_ar": "مدفوع"},
        {"value": "donation", "label_en": "Donation", "label_ar": "تبرع"},
    ],
}
