# Generated by Django 6.0.5 on 2026-05-23 07:18

import apps.core.validators
import django.db.models.deletion
import imagekit.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdPlacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("home_top", "Home Top"),
                            ("home_middle", "Home Middle"),
                            ("properties_list", "Properties List"),
                            ("properties_detail", "Properties Detail"),
                            ("vehicles_list", "Vehicles List"),
                            ("vehicles_detail", "Vehicles Detail"),
                            ("classifieds_list", "Classifieds List"),
                            ("jobs_list", "Jobs List"),
                            ("news_sidebar", "News Sidebar"),
                            ("deals_page", "Deals Page"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                ("width", models.PositiveIntegerField(help_text="px")),
                ("height", models.PositiveIntegerField(help_text="px")),
                ("max_ads", models.PositiveSmallIntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name="AdBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "image",
                    imagekit.models.fields.ProcessedImageField(
                        upload_to="ads/banners/",
                        validators=[
                            apps.core.validators.validate_image_size,
                            apps.core.validators.validate_image_type,
                        ],
                    ),
                ),
                ("url", models.URLField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("impressions", models.PositiveIntegerField(default=0)),
                ("clicks", models.PositiveIntegerField(default=0)),
                (
                    "budget",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(default="SYP", max_length=5)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "advertiser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ad_banners",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "placement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banners",
                        to="advertisements.adplacement",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AdClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("clicked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "banner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="click_records",
                        to="advertisements.adbanner",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-clicked_at"],
            },
        ),
        migrations.CreateModel(
            name="AdImpression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "banner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="impression_records",
                        to="advertisements.adbanner",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-recorded_at"],
            },
        ),
    ]
