import random
import string
from django.contrib.auth.models import AbstractUser, UserManager
from django.db import models
from django.utils import timezone
from datetime import timedelta
from imagekit.models import ProcessedImageField, ImageSpecField
from imagekit.processors import Transpose, ResizeToFill
from apps.core.validators import validate_image_size, validate_image_type


class BarmhaUserManager(UserManager):
    """
    Custom manager that removes 'username' from create_user / create_superuser
    signatures.  Username is auto-generated by User.save().
    """

    def _auto_username(self, email):
        base    = (email or "").split("@")[0][:20].lower() or "user"
        slug    = base
        counter = 1
        while self.filter(username=slug).exists():
            slug = f"{base}{counter}"
            counter += 1
        return slug

    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("Email address is required.")
        email = self.normalize_email(email)
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        # Auto-generate username if not supplied
        if not extra_fields.get("username"):
            extra_fields["username"] = self._auto_username(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        if not extra_fields.get("username"):
            extra_fields["username"] = self._auto_username(email)
        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")
        return self.create_user(email, password, **extra_fields)


class User(AbstractUser):
    """
    Custom user model.

    Authentication:  email (USERNAME_FIELD) or phone via LoginView.
    Username:        auto-generated from the email local part; never shown to
                     end-users but kept in the DB for Django internals / admin.
    Social auth:     handled by allauth + our own GoogleLogin / FacebookLogin
                     views that skip the username requirement entirely.
    """

    USER_TYPES = [
        ("individual",  "Individual"),
        ("agent",       "Real Estate Agent"),
        ("agency",      "Real Estate Agency"),
        ("company",     "Company / Employer"),
        ("freelancer",  "Freelancer"),
        ("merchant",    "Merchant / Business"),
    ]

    # ── Custom manager ─────────────────────────────────────────────────────────
    objects = BarmhaUserManager()

    # ── Make email the primary identifier ─────────────────────────────────────
    email             = models.EmailField(unique=True)          # override blank default
    username          = models.CharField(                       # kept for internals only
        max_length=150, unique=True,
        blank=True,                                             # never required from users
        help_text="Auto-generated internal identifier.",
    )
    USERNAME_FIELD    = "email"
    REQUIRED_FIELDS   = []                                      # no extra prompts for createsuperuser

    # ── Profile fields ─────────────────────────────────────────────────────────
    user_type         = models.CharField(max_length=20, choices=USER_TYPES, default="individual")
    phone             = models.CharField(max_length=20, blank=True)
    whatsapp          = models.CharField(max_length=20, blank=True)
    avatar            = ProcessedImageField(
        upload_to="avatars/",
        processors=[Transpose(), ResizeToFill(400, 400)],
        format="WEBP", options={"quality": 80},
        blank=True, null=True,
        validators=[validate_image_size, validate_image_type],
    )
    avatar_thumbnail  = ImageSpecField(source="avatar", id="core:avatar")
    bio               = models.TextField(blank=True)
    is_verified       = models.BooleanField(default=False)
    language          = models.CharField(max_length=5, default="ar")
    social_avatar_url = models.URLField(blank=True)
    created_at        = models.DateTimeField(auto_now_add=True)
    updated_at        = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "users"

    # ── Auto-generate username from email ──────────────────────────────────────
    def save(self, *args, **kwargs):
        if not self.username:
            base    = (self.email or "").split("@")[0][:20].lower() or "user"
            slug    = base
            counter = 1
            while User.objects.filter(username=slug).exclude(pk=self.pk).exists():
                slug = f"{base}{counter}"
                counter += 1
            self.username = slug
        super().save(*args, **kwargs)


class RealEstateAgency(models.Model):
    name           = models.CharField(max_length=200)
    logo           = ProcessedImageField(
        upload_to="agencies/logos/",
        processors=[Transpose(), ResizeToFill(400, 400)],
        format="WEBP", options={"quality": 80},
        blank=True, null=True,
        validators=[validate_image_size, validate_image_type],
    )
    logo_thumbnail = ImageSpecField(source="logo", spec="core:logo")
    description    = models.TextField(blank=True)
    license_number = models.CharField(max_length=50, blank=True)
    phone          = models.CharField(max_length=20, blank=True)
    whatsapp       = models.CharField(max_length=20, blank=True)
    email          = models.EmailField(blank=True)
    address        = models.TextField(blank=True)
    website        = models.URLField(blank=True)
    verified       = models.BooleanField(default=False)
    properties_for_rent = models.PositiveIntegerField(default=0)
    properties_for_sale = models.PositiveIntegerField(default=0)
    instagram      = models.URLField(blank=True)
    facebook       = models.URLField(blank=True)
    linkedin       = models.URLField(blank=True)
    youtube        = models.URLField(blank=True)
    tiktok         = models.URLField(blank=True)
    created_at     = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "Real Estate Agencies"

    def __str__(self):
        return self.name


class RealEstateAgent(models.Model):
    user            = models.OneToOneField(User, on_delete=models.CASCADE, related_name="agent_profile")
    agency          = models.ForeignKey(RealEstateAgency, null=True, blank=True,
                                        on_delete=models.SET_NULL, related_name="agents")
    license_number  = models.CharField(max_length=50, blank=True)
    languages       = models.JSONField(default=list)
    specializations = models.JSONField(default=list)
    verified        = models.BooleanField(default=False)
    listings_count  = models.PositiveIntegerField(default=0)

    def __str__(self):
        return str(self.user)


class Subscription(models.Model):
    PLANS    = [("free","Free"),("basic","Basic"),("premium","Premium"),("enterprise","Enterprise")]
    SECTIONS = [("properties","Properties"),("vehicles","Vehicles"),("classifieds","Classifieds"),
                ("services","Services"),("jobs","Jobs"),("deals","Deals")]
    user       = models.ForeignKey(User, on_delete=models.CASCADE, related_name="subscriptions")
    plan       = models.CharField(max_length=20, choices=PLANS)
    section    = models.CharField(max_length=20, choices=SECTIONS)
    start_date = models.DateField()
    end_date   = models.DateField()
    is_active  = models.BooleanField(default=True)
    auto_renew = models.BooleanField(default=False)
    price_paid = models.DecimalField(max_digits=10, decimal_places=2, default=0)

    def __str__(self):
        return f"{self.user} - {self.plan}/{self.section}"


class SavedSearch(models.Model):
    user       = models.ForeignKey(User, on_delete=models.CASCADE, related_name="saved_searches")
    section    = models.CharField(max_length=20)
    filters    = models.JSONField()
    name       = models.CharField(max_length=100, blank=True)
    notify     = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user} - {self.name or self.section}"


class Favourite(models.Model):
    CONTENT_TYPES = [
        ("property","Property"),("vehicle","Vehicle"),("classified","Classified"),
        ("service","Service"),("job","Job"),("deal","Deal"),("event","Event"),
    ]
    user         = models.ForeignKey(User, on_delete=models.CASCADE, related_name="favourites")
    content_type = models.CharField(max_length=20, choices=CONTENT_TYPES)
    object_id    = models.PositiveIntegerField()
    created_at   = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ("user", "content_type", "object_id")

    def __str__(self):
        return f"{self.user} - {self.content_type}/{self.object_id}"


class PhoneVerification(models.Model):
    user       = models.ForeignKey(User, on_delete=models.CASCADE, related_name="otp_requests")
    phone      = models.CharField(max_length=20)
    code       = models.CharField(max_length=6)
    is_used    = models.BooleanField(default=False)
    attempts   = models.PositiveSmallIntegerField(default=0)
    expires_at = models.DateTimeField()
    created_at = models.DateTimeField(auto_now_add=True)

    @classmethod
    def create_for_user(cls, user, phone):
        code = "".join(random.choices(string.digits, k=6))
        return cls.objects.create(
            user=user, phone=phone, code=code,
            expires_at=timezone.now() + timedelta(minutes=10),
        )

    def is_valid(self, submitted_code):
        if self.is_used:
            return False, "already_used"
        if self.attempts >= 5:
            return False, "too_many_attempts"
        if timezone.now() > self.expires_at:
            return False, "expired"
        self.attempts += 1
        self.save(update_fields=["attempts"])
        if self.code != submitted_code:
            return False, "invalid_code"
        self.is_used = True
        self.save(update_fields=["is_used"])
        return True, "ok"

    def __str__(self):
        return f"{self.user} - {self.phone}"


class StripeCustomer(models.Model):
    user               = models.OneToOneField(User, on_delete=models.CASCADE, related_name="stripe_customer")
    stripe_customer_id = models.CharField(max_length=100)

    def __str__(self):
        return f"{self.user} - {self.stripe_customer_id}"


class PaymentIntent(models.Model):
    STATUS_CHOICES = [
        ("pending","Pending"),("succeeded","Succeeded"),
        ("failed","Failed"),("cancelled","Cancelled"),
    ]
    user         = models.ForeignKey(User, on_delete=models.CASCADE, related_name="payment_intents")
    amount       = models.DecimalField(max_digits=10, decimal_places=2)
    currency     = models.CharField(max_length=5, default="USD")
    stripe_pi_id = models.CharField(max_length=100)
    status       = models.CharField(max_length=15, choices=STATUS_CHOICES, default="pending")
    created_at   = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user} - {self.amount} {self.currency} [{self.status}]"
