# Generated by Django 5.2.14 on 2026-05-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="subject_type",
            field=models.CharField(
                choices=[
                    ("agent", "Agent"),
                    ("agency", "Agency"),
                    ("provider", "Provider"),
                    ("merchant", "Merchant"),
                    ("freelancer", "Freelancer"),
                    ("company", "Company"),
                    ("showroom", "Showroom"),
                    ("store", "Store"),
                ],
                max_length=15,
            ),
        ),
    ]
